### ISSUE TITLE
Why always pretty json?

### ISSUE THREAD

**Issue by aichholzer** [redcenter/api-design-tips#1]
This

```
{
   "status": 404,
   "message": "Resource not found",
   "meta": {
      "IP": "127.0.0.1",
      "method": "GET"
   }
}
```

is, in essence, incorrect. The API cannot return pretty JSON, per-se. JSON is plain text and it's the header that makes the receiving party understand what it is. It is up to the client to make it look "pretty". If you are talking about actually formatting the JSON response so it "looks nice", then you are just adding unnecessary overhead.

**Comment by redcenter** [comment]
I think this is a personal preference. The example shows exactly the difference between both approaches and I bet most developers love my solution, because it's user-friendly.

And the performance boost is minimal. If that's will be the difference between a fast and slow API, you have a REAL crappy setup to begin with.

If an API designer is really, really thinks this makes a difference but still wants to use it in non-production env's, he/she can always make pretty json an option (tru headers or query params).

But for now: this is my personal preference and I have heard from many dev's they like it.

**Comment by aichholzer** [comment]
In my opinion, you are trying to solve an issue that should fall completely on the API user. An API's intention it to be fast, lean and to serve data, plain data. Any developer would know how to deal with the JSON to make it look nice, which is something that should only, ever, be done during development time.

You approach is returning a response that just makes the API user more lazy, not more efficient. I does not have anything to do with designing a great API.
